### ISSUE TITLE
Consider alternatives for username/password for key vault and registry access

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/notation#143]
The current notation cli either requires -u/-p to be passed to `notation sign`, or `$NOTATION_USERNAME` and `$NOTATION_PASSWORD` environment variables to be set.

When combined with a keyvault extension this means users must set the username/passowrd for their keyvault provider and the registry. 

This has added some complications, leading to confusion and errors.

I can think of two distinct scenarios:

1. The same credential (username) could be given access to both the registry and key vault. In this case, setting one set of user/password variables would suffice.
2. Different credentials are used for access to the registry and key vault. 

If we assume 2 is needed for flexibility, how can we optimize for the simplistic scenarios, while enabling the flexibility?

Should we depend on environment variables?

For Azure, Azure nodes can be configured with a managed identity. This avoids any username/passwords being store, any any key rotation scenarios. This can be applied to the `notation-azure-kv` binary, but not in the `notation` cli. 

The current extensibility spec focuses on remote signing, but ignores auth extensibility for various registries. Should the keyvault extension be updated to enable auth extensibility as well?

**Comment by sudo-bmitch** [comment]
I instinctively want to push this into the extensibility layer and get rid of having notation itself handle these options for the key management. They make sense for registries since that interface is fairly standardized, but that doesn't exist on the signing key side.

On the docker side, the closest equivalent is the various drivers and driver options passed as one flag with a comma separated value string. When dealing with tools like vault and various cloud CLIs, they look for credentials and settings in environment variables and well known files.

Perhaps a combination of the two handled by each plugin, where notation passes the options CLI string to the plugin, which can be used to override the default settings found in the plugin specific environment and/or files.

**Comment by shizhMSFT** [comment]
Since it is about the registry credentials, the `notation` CLI can reuse the [credential store](https://docs.docker.com/engine/reference/commandline/login/#credentials-store) from [docker CLI](https://github.com/docker/cli).

**Comment by SteveLasker** [comment]
i like it, when the docker cli is installed. But, what do we do if someone is building with other tools? We have the same general issue for oras. Or, on the node that runs verify? On the verify node, we can likely take advantage of MI. For sign, many can use MI, but not all.

**Comment by shizhMSFT** [comment]
@SteveLasker For Ratify, it can leverage the `oras-go`, `notation-go`, MSAL libraries directly without bothering the CLIs.

**Comment by SteveLasker** [comment]
@sudo-bmitch was right-on, and we've moved this to the [plug-in spec](https://github.com/notaryproject/roadmap/issues/26). The default sign/push flow would only need to deal with the registry as the default provider can do local signing. Any remote signing would require a plug-in.

Closing
