### ISSUE TITLE
notation remote signing error

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notation#268]
**Summary**
notation remote signing error on main branch. Signing key and certs are stored in Azure KV.

**Steps to reproduce issue**

1. Build notation binary from main branch
2. Follow the flow here https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tutorial-sign-build-push
3. Execute notation sign --key $KEY_NAME $IMAGE according to step 3 under https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tutorial-sign-build-push#build-and-sign-a-container-image

**Logs**

> notation sign --key $KEY_NAME $IMAGE
> 2022/07/26 17:07:15 failed to sign digest. error : generate-signature command failed: azure-kv: ERROR: failed to sign payload: unavailable hash function: unknown hash value 0

**Comment by chloeyin** [comment]
I will take a look at it.

**Comment by patrickzheng200** [comment]
A quick summary of this issue: The [notation-azure-kv](https://github.com/Azure/notation-azure-kv) plugin is calling a previous version of notation-go. Notation would create a GenerateSignatureRequest and send it to the notation-azure-kv plugin. Inside this request, there is a field called Hash, and the value is "SHA-256" (taking SHA256 as an example). However, notation-azure-kv expects "SHA_256", note the underscore instead of dash. It cannot find "SHA-256", hence failed to sign. @chloeyin 's  PR fixes this issue.

**Comment by gokarnm** [comment]
Please check my comment on related [notation-core-go PR](https://github.com/notaryproject/notation-core-go/pull/20#issuecomment-1205529607). IMO we should update the spec in this case.

**Comment by dtzar** [comment]
Per the notation call today, we decided we are going to just keep this inconsistency in alpha.3 to not delay the release.  Shiwei's team already has this fixed by converting string constants to also help support COSE signing and will release a PR to convert the types sooner than later.
