### ISSUE TITLE
 Release v1.0.0-rc.5 for notation

### ISSUE THREAD

**Issue by priteshbandi** [notaryproject/notation#661]
Release `v1.0.0-rc.5` for `notation`:

- [ ] Fix https://github.com/notaryproject/notation/issues/659
- [x] https://github.com/notaryproject/notation/issues/660
- [ ] Cut branch named `v1.0.0-rc.5` based on commit of above fix.
- [ ] Cut a tag named `v1.0.0-rc.5`

@priteshbandi @patrickzheng200 @JeyJeyGao @shizhMSFT @vaninrao10 @rgnote @gokarnm @iamsamirzon @toddysm @FeynmanZhou @NiazFK @justincormack @SteveLasker

**Comment by yizha1** [comment]
What is the scope of rc.5? I suggest the follows:
- https://github.com/notaryproject/notation/issues/659
- https://github.com/notaryproject/notation/issues/660

**Comment by FeynmanZhou** [comment]
LGTM to have an RC.5 release before the stable v1 release.

**Comment by yizha1** [comment]
LGTM for RC.5

**Comment by toddysm** [comment]
LGTM

**Comment by rgnote** [comment]
LGTM

**Comment by iamsamirzon** [comment]
LGTM

**Comment by yizha1** [comment]
@priteshbandi there were other PRs out of the scope was merged. We should align on the commit we want to cut for this release

**Comment by shizhMSFT** [comment]
Additionally, the release vote for the `notation` repo cannot be conveyed to other repos. We need individual release vote issue for `notation-go` and `notation-core-go`.

**Comment by yizha1** [comment]
@shizhMSFT Thanks Shiwei for pointing out. The release governance document needs to be replenished. Currently it is preliminary, and under notation CLI repo, see https://github.com/notaryproject/notation/blob/main/RELEASE_CHECKLIST.md. We should improve it, so that everyone can follow. cc @FeynmanZhou

**Comment by priteshbandi** [comment]
@yizha1 we can create new branch and cherrypick commits for rc5 (we need to anyway create a new branch). Also, we can realign on commits, whatever works for you.

**Comment by FeynmanZhou** [comment]
@yizha1  We will refactor the Release checklist and Release Management from the overall Notary project's point of view instead of the Notation CLI project only. 

@priteshbandi Considering we are preparing for an RC release, it's still acceptable to include the additional bug fixes included in the following [commits](https://github.com/notaryproject/notation/commits/main) and plus https://github.com/notaryproject/notation/pull/670.  IMO, it's not necessary to create a new branch and cherry-pick specified commits this time since it may complicate the regular release process.   

![image](https://github.com/notaryproject/notation/assets/40452856/b9a11a68-d823-4fa4-9a05-39aeda19a0f1)

**Comment by yizha1** [comment]
@priteshbandi @shizhMSFT @FeynmanZhou maybe we can close this issue, as the original problem was solved to align on the scope of RC-5 releases. Since we are going to include PRs like bug fixing, I suggest creating a new issue to vote for release.

**Comment by priteshbandi** [comment]
Opened issue to vote for rc5 release https://github.com/notaryproject/notation/issues/671
