### ISSUE TITLE
Invalid link in `notation login` error message

### ISSUE THREAD

**Issue by Wwwsylvia** [notaryproject/notation#783]
### What is not working as expected?

The troubleshooting link in the error message of `notation login` is not working (404 Not Found).

> Error: failed to log in to docker.io: the credential could not be saved because a credentials store is required to securely store the password. See https://notaryproject.dev/docs/how-to/registry-authentication/

Looks like the corresponding page has been moved to https://notaryproject.dev/docs/user-guides/how-to/registry-authentication/.

### What did you expect to happen?

The error message should be updated with the correct link.

### How can we reproduce it?

Run `notation login` on a Linux machine with no credentials store installed.

### Describe your environment

Notation installation method : wget
OS version: Ubuntu 18.04.4 LTS (WSL)
Shell type: Bash on Windows

### What is the version of your Notation CLI or Notation Library?

Version:     1.0.0
Go version:  go1.20.7
Git commit:  80e3fc4e2eeb43ac00bc888cf41101f5c56f1535

**Comment by FeynmanZhou** [comment]
I will investigate a redirection solution for this broken link.

**Comment by priteshbandi** [comment]
IMO we should avoid adding link in CLI and instead maintain error message FAQ in the [https://notaryproject.dev/](https://notaryproject.dev/docs/how-to/registry-authentication/) website. This way we can update/archive FAQ without much effort

**Comment by FeynmanZhou** [comment]
@priteshbandi Thanks for your advice. From my observation, the common practice is to use versioned URL in the CLI/GUI. The root cause of this issue is the Notary Project website lacks of version control so we can't use a versioned permanent doc link in CLI. 
We are working on supporting version control in the the Notary Project website  https://github.com/notaryproject/notaryproject.dev/issues/350
